### Задание 1:



Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк 
и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, 
а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это 
признак, а строка - наблюдение. 

In [26]:
import numpy as np

a=np.zeros([5,2])
a[:,0]=[1,2,3,3,1]
a[:,1]=[6,8,11,10,7]
a=np.array(a)
a

array([[ 1.,  6.],
       [ 2.,  8.],
       [ 3., 11.],
       [ 3., 10.],
       [ 1.,  7.]])

Затем найдите среднее значение по каждому признаку, 
используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно 
быть 2 элемента.

In [27]:
c=a.mean(axis=0)
c

array([2. , 8.4])

### Задание 2:



Вычислите массив a_centered, отняв от значений массива “а” средние значения 
соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно 
производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [28]:
a_centered=a-c
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3:

Найдите скалярное произведение столбцов массива a_centered. В результате должна
 получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где 
 N - число наблюдений.

In [29]:
f=np.dot(a_centered[:,0], a_centered[:,1])/ (len(a_centered)-1)
f

2.0

In [30]:
np.cov(a.T)[0,1]

2.0